import type { Vec2 } from '../shared/Vec2.js';

/**
 * Discriminant for module type.
 * - `source`: Generates flow (pumps stock value UP).
 * - `stock`: Accumulates flow — the central measurement target.
 * - `sink`: Absorbs flow (drains stock value DOWN).
 *
 * Consumers narrow `ModuleNode` to the concrete subtype by checking
 * `node.type` at runtime.
 */
export type ModuleType = 'source' | 'stock' | 'sink';

/**
 * Base module placed on the infinite canvas.
 *
 * Every module has a unique id, a type discriminant, and a 2D position.
 * The optional `label` is user-facing display text (defaults to empty string
 * in UI if omitted).
 *
 * ALL properties are plain data — no Function, Symbol, Date, or DOM references.
 * This guarantees that `structuredClone` and `JSON.stringify` round-trip
 * without data loss.
 */
export interface ModuleNode {
  /** Unique identifier — generated by the mutation layer (e.g. `crypto.randomUUID()`). */
  readonly id: string;
  /** Discriminant for narrowing to concrete subtypes. */
  readonly type: ModuleType;
  /** Position on the infinite canvas in world-space coordinates. */
  position: Vec2;
  /** Optional user-facing label. */
  label?: string;
  /** Optional semantic color (e.g. '#90EE90' for source, '#8B0000' for sink). */
  color?: string;
}

/**
 * Stock node — the central measurement target that accumulates flow over time.
 *
 * Extends `ModuleNode` with simulation-specific fields:
 * - `value`: Current accumulated quantity.
 * - `capacity`: Maximum capacity (used for fill-level rendering and countdown
 *   calculation).
 * - `initialValue`: The value to reset to on simulation reset.
 */
export interface StockNode extends ModuleNode {
  readonly type: 'stock';
  /** Current accumulated quantity. Updated every simulation tick. */
  value: number;
  /** Maximum capacity. Used for fill-level animation and countdown-to-full. */
  capacity: number;
  /** The value to restore on RESET. */
  initialValue: number;
}

/**
 * Source node — generates flow into connected stocks.
 *
 * By convention, the optional `color` is a CSS color string (e.g. `'#90EE90'`
 * for light green). Per UX-DR3, sources use a pool of 5 light colors.
 * The first source placed defaults to light green.
 */
export interface SourceNode extends ModuleNode {
  readonly type: 'source';
  /** CSS color string from the light-color palette. */
  color?: string;
}

/**
 * Sink node — absorbs flow from connected stocks.
 *
 * By convention, the optional `color` is a CSS color string (e.g. `'#8B0000'`
 * for dark red). Per UX-DR3, sinks use a pool of 5 dark colors.
 * The first sink placed defaults to dark red.
 */
export interface SinkNode extends ModuleNode {
  readonly type: 'sink';
  /** CSS color string from the dark-color palette. */
  color?: string;
}

/**
 * Directed connection between two modules.
 *
 * For valid models: `fromId` points to a source or stock; `toId` points to a
 * stock or sink. Source→Sink (skipping stock) connections are flagged as
 * invalid by the stack-completeness validator (Story 4.6).
 *
 * `formulaStr` is a STRING, never a Function. The simulation engine's
 * expression parser evaluates it at tick time. This is a hard constraint per
 * Best Practice Paradigm — it prevents arbitrary code execution and guarantees
 * JSON serialization safety.
 */
export interface Connection {
  /** Unique identifier — generated by the mutation layer. */
  readonly id: string;
  /** Id of the upstream module (source or stock). */
  fromId: string;
  /** Id of the downstream module (stock or sink). */
  toId: string;
  /** Constant flow rate applied per simulation tick. */
  rate: number;
  /**
   * Formula expression as a STRING.
   *
   * Examples:
   * - `"5"` — constant rate of 5 units/tick
   * - `"sin(t * 0.5) * 10"` — time-varying rate (Growth phase FR30)
   *
   * NEVER store a Function or use `eval()` on this value at rest.
   * The formula parser/evaluator (Story 4.4) operates on this string at
   * simulation time.
   */
  formulaStr: string;
}

/**
 * Complete model state at a point in time.
 *
 * This is the core data structure that `structuredClone` snapshots capture
 * (for undo/redo, HistoryManager, and the EventBus snapshot bridge).
 *
 * Every mutation (create/delete/move module, create/delete connection, edit
 * rate/formula) produces a NEW `GraphState` with an incremented `version`.
 *
 * All values are POJO — no classes, getters/setters, prototype chains, or
 * non-serializable references. This guarantees:
 * 1. `structuredClone()` works without custom clone logic
 * 2. `JSON.stringify` / `JSON.parse` round-trips without data loss
 * 3. Zero runtime overhead from instance methods
 */
export interface GraphState {
  /** All modules on the canvas, keyed by `id`. */
  nodes: Record<string, ModuleNode>;
  /** All connections, keyed by `id`. */
  connections: Record<string, Connection>;
  /**
   * Monotonically incrementing integer.
   *
   * Every mutation increments this by 1. Serves as:
   * - A dirty flag for renderers (has state changed since last frame?)
   * - A cache-busting key for memoized selectors (future Growth phase)
   * - A debugging aid (trace state transitions in console)
   */
  version: number;
  /**
   * Currently selected module ids.
   *
   * Part of `GraphState` per Architecture Decision 5 — restoring a full
   * snapshot automatically restores selection state. Undo/redo does NOT
   * require separate selection-restoration logic.
   */
  selectedModuleIds: string[];
  /**
   * Story 3.7 — Currently selected connection ids.
   *
   * Stored in GraphState so undo/redo automatically restore connection
   * selection state alongside module selection.
   */
  selectedConnectionIds: string[];
}
